---
- name: Create pods using deployment
  hosts: kubernetes
  become: true
  user: root

  tasks:
  - name: create a deployment
    command: kubectl apply -f kttyper-deployment.yml
    args:
      chdir: /opt/k8s-lab
  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment.v1.apps/kttyper-deployment
