---
- name: create service for deployment
  hosts: kubernetes
  become: true
  user: root

  tasks:
  - name: create a service
    command: kubectl apply -f kttyper-service.yml
    args:
      chdir: /opt/k8s-lab
